name: Build Solution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print current directory
      run: |
        pwd

    - name: List files in directory
      run: |
        ls -la

    - name: Print value of Solution_Name variable
      run: |
        echo "Solution name: $env:Solution_Name"

    - name: Restore and build solution
      run: |
        msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
